package io.github.frankois944.spmForKmp.tasks.utils

import java.io.File
import java.time.Instant
import java.util.Locale
import java.util.concurrent.ConcurrentLinkedDeque

/**
 * Minimal task tracer to measure durations of named segments and generate a simple HTML report.
 */
internal class TaskTracer(
    private val title: String,
    private val isEnabled: Boolean = true,
    private val outputFile: File,
) {
    private val root = Span(name = title, start = Instant.now().toEpochMilli())
    private val stack = ConcurrentLinkedDeque<Span>().apply { push(root) }

    fun <T> trace(
        name: String,
        block: () -> T,
    ): T {
        if (isEnabled) {
            val parent = stack.peek() ?: root
            val span = Span(name = name, start = Instant.now().toEpochMilli())
            parent.children.add(span)
            stack.push(span)
            return try {
                block()
            } finally {
                span.end = Instant.now().toEpochMilli()
                stack.pop()
            }
        } else {
            return block()
        }
    }

    fun finish() {
        if (isEnabled && root.end == null) root.end = Instant.now().toEpochMilli()
    }

    fun writeHtmlReport() {
        if (isEnabled) {
            finish()
            outputFile.parentFile.mkdirs()
            outputFile.writeText(renderHtml())
        }
    }

    @Suppress("LongMethod")
    private fun renderHtml(): String {
        val totalMs = root.durationMillis()

        val body =
            buildString {
                append("<header class='header'>")
                append("<h1 class='title'>${esc(title)}</h1>")
                append("<div class='meta'>")
                append("<span class='pill'>Total <strong>$totalMs ms</strong></span>")
                append("<span class='pill'>Spans <strong>${root.children.size}</strong></span>")
                append("</div>")
                append("</header>")

                append("<section class='card'>")
                append("<table class='trace' aria-label='Task trace summary'>")
                append(
                    """
                    <thead>
                      <tr>
                        <th class="col-span" scope="col">Span</th>
                        <th class="col-num" scope="col">Total (ms)</th>
                        <th class="col-num" scope="col">Self (ms)</th>
                        <th class="col-pct" scope="col">% of total</th>
                        <th class="col-num" scope="col">Children</th>
                      </tr>
                    </thead>
                    <tbody>
                    """.trimIndent(),
                )

                root.children.forEach { child ->
                    append(renderRow(child, totalMs, 0))
                }

                append("</tbody></table>")
                append("</section>")

                append("<footer class='footer'>Generated by TaskTracer</footer>")
            }

        return """
            <!doctype html>
            <html lang="en">
              <head>
                <meta charset="utf-8">
                <meta name="viewport" content="width=device-width, initial-scale=1">
                <title>${esc(title)} - Trace</title>
                <style>
                  :root {
                    --bg: #0b1020;
                    --card: rgba(255,255,255,0.06);
                    --card-border: rgba(255,255,255,0.10);
                    --text: rgba(255,255,255,0.92);
                    --muted: rgba(255,255,255,0.70);
                    --muted2: rgba(255,255,255,0.55);
                    --accent: #7c5cff;
                    --accent2: #35d0ff;
                    --row: rgba(255,255,255,0.03);
                    --row2: rgba(255,255,255,0.015);
                    --shadow: 0 12px 30px rgba(0,0,0,0.35);
                    --mono: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace;
                    --sans: ui-sans-serif, system-ui, -apple-system, Segoe UI, Roboto, Helvetica, Arial, "Apple Color Emoji", "Segoe UI Emoji";
                  }
                  @media (prefers-color-scheme: light) {
                    :root {
                      --bg: #f6f7fb;
                      --card: rgba(255,255,255,0.9);
                      --card-border: rgba(10,18,40,0.10);
                      --text: rgba(10,18,40,0.92);
                      --muted: rgba(10,18,40,0.70);
                      --muted2: rgba(10,18,40,0.55);
                      --row: rgba(10,18,40,0.04);
                      --row2: rgba(10,18,40,0.02);
                      --shadow: 0 12px 30px rgba(10,18,40,0.12);
                    }
                  }
                  * { box-sizing: border-box; }
                  body {
                    margin: 0;
                    padding: 28px;
                    font-family: var(--sans);
                    color: var(--text);
                    background:
                      radial-gradient(1000px 500px at 15% 0%, rgba(124,92,255,0.25), transparent 55%),
                      radial-gradient(900px 420px at 85% 10%, rgba(53,208,255,0.18), transparent 55%),
                      var(--bg);
                  }
                  .header {
                    max-width: 1100px;
                    margin: 0 auto 16px auto;
                    display: flex;
                    align-items: baseline;
                    justify-content: space-between;
                    gap: 16px;
                    flex-wrap: wrap;
                  }
                  .title {
                    margin: 0;
                    font-size: 20px;
                    letter-spacing: 0.2px;
                  }
                  .meta { display: flex; gap: 10px; flex-wrap: wrap; }
                  .pill {
                    display: inline-flex;
                    gap: 8px;
                    align-items: baseline;
                    padding: 6px 10px;
                    border-radius: 999px;
                    background: var(--card);
                    border: 1px solid var(--card-border);
                    box-shadow: var(--shadow);
                    color: var(--muted);
                    font-size: 12px;
                    line-height: 1;
                  }
                  .pill strong { color: var(--text); font-family: var(--mono); font-weight: 650; }
                  .card {
                    max-width: 1100px;
                    margin: 0 auto;
                    background: var(--card);
                    border: 1px solid var(--card-border);
                    border-radius: 14px;
                    box-shadow: var(--shadow);
                    overflow: hidden;
                  }
                  table.trace {
                    width: 100%;
                    border-collapse: separate;
                    border-spacing: 0;
                  }
                  thead th {
                    position: sticky;
                    top: 0;
                    z-index: 2;
                    background: linear-gradient(to bottom, rgba(0,0,0,0.12), rgba(0,0,0,0.04));
                    backdrop-filter: blur(10px);
                    color: var(--muted);
                    text-align: left;
                    font-weight: 600;
                    font-size: 12px;
                    padding: 12px 12px;
                    border-bottom: 1px solid var(--card-border);
                  }
                  tbody td {
                    padding: 10px 12px;
                    border-bottom: 1px solid rgba(255,255,255,0.06);
                    vertical-align: middle;
                    font-size: 13px;
                  }
                  tbody tr:nth-child(odd) { background: var(--row); }
                  tbody tr:nth-child(even) { background: var(--row2); }
                  tbody tr:hover { background: rgba(124,92,255,0.12); }
                  .col-num { text-align: right; font-family: var(--mono); }
                  .col-pct { text-align: right; }
                  .col-span { width: 46%; }
                  .span-name {
                    display: inline-flex;
                    align-items: center;
                    gap: 8px;
                    padding-left: calc(var(--depth, 0) * 14px);
                    white-space: nowrap;
                    overflow: hidden;
                    text-overflow: ellipsis;
                    max-width: 100%;
                  }
                  .dot {
                    width: 8px;
                    height: 8px;
                    border-radius: 999px;
                    background: linear-gradient(135deg, var(--accent), var(--accent2));
                    box-shadow: 0 0 0 3px rgba(124,92,255,0.15);
                    flex: 0 0 auto;
                  }
                  .badge {
                    margin-left: 6px;
                    font-family: var(--mono);
                    font-size: 11px;
                    color: var(--muted2);
                    border: 1px solid var(--card-border);
                    background: rgba(255,255,255,0.05);
                    padding: 2px 6px;
                    border-radius: 999px;
                  }
                  .pct-wrap {
                    display: inline-flex;
                    align-items: center;
                    justify-content: flex-end;
                    gap: 10px;
                    width: 100%;
                  }
                  .pct-val { font-family: var(--mono); color: var(--muted); min-width: 62px; text-align: right; }
                  .bar {
                    height: 8px;
                    width: 110px;
                    background: rgba(255,255,255,0.10);
                    border: 1px solid rgba(255,255,255,0.10);
                    border-radius: 999px;
                    overflow: hidden;
                  }
                  .bar > i {
                    display: block;
                    height: 100%;
                    width: 0%;
                    background: linear-gradient(90deg, var(--accent), var(--accent2));
                  }
                  .footer {
                    max-width: 1100px;
                    margin: 10px auto 0 auto;
                    color: var(--muted2);
                    font-size: 12px;
                    text-align: right;
                  }
                </style>
              </head>
              <body>
                $body
              </body>
            </html>
            """.trimIndent()
    }

    @Suppress("MagicNumber")
    private fun renderRow(
        span: Span,
        totalMs: Long,
        depth: Int,
    ): String {
        val ms = span.durationMillis()
        val selfMs = span.selfDurationMillis()
        val pct = if (totalMs > 0) (ms.toDouble() / totalMs * 100).coerceIn(0.0, 100.0) else 0.0
        val pctLabel = String.format(locale = Locale.US, "%.1f", pct)

        val row =
            """
            <tr>
              <td class="col-span" style="--depth:$depth">
                <span class="span-name">
                  <span class="dot" aria-hidden="true"></span>
                  <span>${esc(span.name)}</span>
                  <span class="badge" title="Children">${span.children.size}</span>
                </span>
              </td>
              <td class="col-num">$ms</td>
              <td class="col-num">$selfMs</td>
              <td class="col-pct">
                <span class="pct-wrap">
                  <span class="bar" aria-hidden="true"><i style="width:$pctLabel%"></i></span>
                  <span class="pct-val">$pctLabel%</span>
                </span>
              </td>
              <td class="col-num">${span.children.size}</td>
            </tr>
            """.trimIndent()

        val children = span.children.joinToString("") { renderRow(it, totalMs, depth + 1) }
        return row + children
    }

    @Suppress("MagicNumber")
    private fun renderSpan(
        span: Span,
        totalMs: Long,
    ): String {
        val ms = span.durationMillis()
        val pct = if (totalMs > 0) (ms.toDouble() / totalMs * 100).coerceAtMost(100.0) else 0.0
        val barWidth = pct
        val childrenHtml =
            if (span.children.isNotEmpty()) {
                "<ul>" + span.children.joinToString("") { renderSpan(it, totalMs) } + "</ul>"
            } else {
                ""
            }
        return """
                                                                                                                                                                                    <li>
                                                                                                                                                                                      <div><strong>${
            esc(
                span.name,
            )
        }</strong> — $ms ms <span class=\"pct\">(${
            String.format(
                locale = Locale.US,
                "%.1f",
                pct,
            )
        }%)</span></div>
                                                                                                                                                                                      <div class=\"bar\" style=\"width:${
            String.format(
                locale = Locale.US,
                "%.1f",
                barWidth,
            )
        }%\"></div>
                                                                                                                                                                                      $childrenHtml
                                                                                                                                                                                    </li>
            """.trimIndent()
    }

    private fun Span.durationMillis(): Long {
        val endInstant = end ?: Instant.now().toEpochMilli()
        return endInstant - start
    }

    private fun Span.selfDurationMillis(): Long {
        val childrenMs = children.sumOf { it.durationMillis() }
        val total = durationMillis()
        return (total - childrenMs).coerceAtLeast(0)
    }

    private fun esc(s: String): String =
        s
            .replace("&", "&amp;")
            .replace("<", "&lt;")
            .replace(">", "&gt;")
            .replace("\"", "&quot;")

    private data class Span(
        val name: String,
        val start: Long,
        var end: Long? = null,
        val children: MutableList<Span> = mutableListOf(),
    )
}
