name: Build and Tests

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'website/**'
      - 'BinaryPackageSource/**'
      - '.idea/**'

concurrency:
  # Use a unique identifier for the workflow cancellation group.
  # Most commonly, the branch name or pull request reference.
  group: ${{ github.ref }} # Cancels workflows for the same branch or PR
  cancel-in-progress: true # Automatically cancels in-progress workflows

jobs:
  gradle:
    runs-on: macos-latest
    env:
      GRADLE_PUBLISH_KEY: ${{ secrets.GRADLE_PUBLISH_KEY }}
      GRADLE_PUBLISH_SECRET: ${{ secrets.GRADLE_PUBLISH_SECRET }}
    if: ${{ !contains(github.event.head_commit.message, 'ci skip') }}
    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'jetbrains'
          java-version: '17'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Cache Konan
        id: cache-konan
        uses: actions/cache@v4
        with:
          path: ~/.konan
          key: ${{ runner.os }}-konan
      - name: Cache example
        id: cache-example-scratch
        uses: actions/cache@v4
        with:
          path: |
            example/build/spmKmpPlugin
            example/iosApp/spm
            example/iosApp/build
            example/SPM
          key: ${{ runner.os }}-example-snapshot
      - name: Cache Gradle Caches
        uses: gradle/actions/setup-gradle@v4
      - name: test iosExampleApp
        run: xcodebuild -project iosApp.xcodeproj -scheme iosApp -configuration Debug -destination 'platform=iOS Simulator,name=iPhone SE (3rd generation)' -derivedDataPath "./build" -clonedSourcePackagesDirPath "./spm" clean test | xcpretty
        working-directory: "example/iosApp"
